name: spot
description: Find local video posts
version: 1.3.4+56
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.8.0
  flutter_bloc: ^7.1.0
  google_maps_flutter: ^2.0.1
  video_player: ^2.0.2
  flutter_ffmpeg: ^0.4.0
  path_provider: ^2.0.1
  geolocator: ^7.0.1
  supabase: ^0.2.4
  flutter_feather_icons: ^2.0.0+1
  flutter_secure_storage: ^4.1.0
  image_picker: ^0.7.4
  flutter_cache_manager: ^3.0.1
  flutter_markdown: ^0.6.1
  rxdart: ^0.26.0
  geocoding: ^2.0.0
  share: ^2.0.1
  firebase_core: ^1.2.1
  firebase_analytics: ^8.1.1
  flutter_video_info: ^1.2.0
  shared_preferences: ^2.0.6
  google_maps_cluster_manager: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  mocktail: ^0.1.2
  very_good_analysis: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter:
  assets:
    - assets/images/
    - assets/md/
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/launcher/icon.png'
  adaptive_icon_foreground: 'assets/launcher/foreground.png'
  adaptive_icon_background: 'assets/launcher/background.png'
