name: CD_iOS

on:
  push:
    paths:
        - "pubspec.yaml"
        
  pull_request:
    paths:
        - "pubspec.yaml"

jobs:
  ios-build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: '2.2.0'
      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed lib test

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # Build ios app
      - run: flutter build ios --release --no-codesign --flavor production --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_ANNON_KEY=${{ secrets.SUPABASE_ANNON_KEY }}

      - name: Release
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          cd ios
          fastlane release
